version: '3'

services:
  dev:
    restart: always
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
    - '81:3000'
    expose:
      - '81'
    volumes:
    - /app/node_modules
    - .:/app
    environment:
      - DB_HOST=192.168.100.27
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=kodipoint_test
      - JWT_SECRET=12345qwerty
      - EMAIL_SECRET=91lx5912clT
      - ADMIN_EMAIL=nascal3@gmail.com
      - SMS_API_USER=sandbox
      - SMS_API_KEY=027d931a0d3fee29b96a0784cc337ff570af638547b143eba67d1f1b9f8a3a38
      - PORT=3000
    command: ["nodemon", "app.js"]

  web:
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    ports:
    - '80:3000'
    environment:
      - DB_HOST=192.168.99.100
      - DB_USER=root
      - DB_PASSWORD=P@$$w0rd
      - DB_NAME=kodipoint_test
      - JWT_SECRET=12345qwerty
      - EMAIL_SECRET=91lx5912clT
      - ADMIN_EMAIL=nascal3@gmail.com
      - SMS_API_USER=sandbox
      - SMS_API_KEY=027d931a0d3fee29b96a0784cc337ff570af638547b143eba67d1f1b9f8a3a38
      - PORT=3000
